final_project_dbt_group4:
  outputs:
    stg:
      dataset: dbt_final_project_g4
      fixed_retries: 1
      keyfile: /home/avalon/Data-Fellowship-11/dbt_env/service-accounts/service-account-g4-dbt.json
      method: service-account
      priority: interactive
      project: "final-project-df11"
      threads: 3
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: dbt_final_project_g4
      fixed_retries: 1
      keyfile: /home/avalon/Data-Fellowship-11/dbt_env/service-accounts/service-account-g4-dbt.json
      method: service-account
      priority: interactive
      project: "final-project-df11"
      threads: 3
      timeout_seconds: 300
      type: bigquery
  target: prod
